# Site settings
title: 루우씨의 키토제닉이야기
tagline: 내 몸에 키토제닉 식단 생체 실험 중
description: "두뇌를 리부트 하기위해 나에게 맞는 저탄고지 식단을 찾고있습니다."
url: "https://lucyketogenic.com"
author:
  name: "루우씨"
  email: "ketogenic@kakao.com"
  url: "https://lucyketogenic.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown


permalink: /:title
paginate: 8


# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 블로그 disqus shortname
disqus:
  shortname: lucy-ketogenic
